#!/usr/bin/env node
// StickFight DBZ sprites: Vegeta (26x56), Piccolo (25x56), Krillin (33x45), Beerus (32x57), Whis (40x66), Trunks (28x46), Jiren (43x56). All face right.
// Each sprite = palette (letter -> hex colour) + rows of letters ('.' = transparent).
// Usage:  node dbz_sprites.js [outDir]      -> writes one PNG per character
//         node dbz_sprites.js [outDir] --scale 8   -> also writes 8x previews
// No dependencies (uses Node's built-in zlib to write PNGs).
const fs = require('fs'), path = require('path'), zlib = require('zlib');

const SPRITES = {
  vegeta: {
    palette: {"a": "333333", "b": "000000", "c": "fdd5a8", "d": "a88b6a", "e": "d9b48a", "f": "b8b8b8", "g": "ffffff", "h": "e0e0e0", "i": "040430", "j": "000048", "k": "000080", "l": "ffff00", "m": "ffe600", "n": "c4aa00"},
    rows: [
      "...a......................",
      "...aaaa...................",
      "...aaaa...................",
      "...baaaaaaaa...a..........",
      "...bbbbaaaaaaa.ba.........",
      "...bbbbaaaaaaa.ba.........",
      "...bbbbbbbbbaaabba........",
      "...bbbbbbbbbbbaabbaa......",
      "...bbbbbbbbbbbaabbaa......",
      "a..bbbbbbbbbbbbbabbba.....",
      "aaabbbbbbbbbbbbbbbbba.....",
      "aaabbbbbbbbbbbbbbbbba.....",
      "baaabbbbbbbbbbbbbbbbba....",
      "bbbbabbbbbbbbbbbbbbbbb....",
      "bbbbabbbbbbbbbbbbbbbbb....",
      ".bbbbaabbbbbbbbbbbbbbbb...",
      ".bbbbbbbbbbbcdbbbbbbbbb...",
      "...bbbbbbbbdcccdbbbbbdb...",
      "aaaabbbbbbbdccccdbbbbdb...",
      ".bbbabbbbbbecccccebbceb...",
      "...bbbbbbbbcccccccccccb...",
      "....bbbbddbcbbbccccccbb...",
      ".......bccecbfgbccccbhb...",
      ".......bccccchgbbcbbbgb...",
      "........bbbdcccccccccdb...",
      ".......bbbibeccbbbcceb....",
      ".....bbjkkkkbbdececcb.....",
      "....bjjbkkkjbgbbbbbbfb....",
      "....bkkbkkkbggghbhggghb...",
      "...bibbkkkbhgggggbggggb...",
      "...bkkkkjjbbghfbbbbbhb....",
      "...bbkkkbbbfbbblllllbb....",
      ".bbkkkkbggbhgbbbbbbbbib...",
      ".bbikjjbgggbgbmmmmmmbkb...",
      "bbbbbbbggggbhgbbbbbbbbb...",
      "bffghbbggggbbbbbbbbbbfgb..",
      "bffghbbggggbbbbbbbbbbfgb..",
      "bhhgbbbbgggbfhggggffbgbb..",
      "bgggghhbggbbbbbbbbbbbgbhbb",
      "bggggbbgbbikiiikkiiibhbgbb",
      "bhhbgbbgbbkkkkkkkbkkibgfbb",
      ".bbbfbbbiikbkibikbkkibbb..",
      "....bbbbiikbib.bikbbkb....",
      ".....bbbkkbkib.bikbbkb....",
      ".....bbbkkbkib.bikbbkb....",
      ".....bbkbbkkkb.bkkkkib....",
      "....biikkkkib..bikkkib....",
      "....bbbbkkkib..bbbbbbb....",
      "....bbbbkkkib..bbbbbbb....",
      "....bhhgbbbb...bhghhfb....",
      "...bfgggggfb...bggggfb....",
      "...bfgggggfb...bggggfb....",
      "...bbbbhggb....bfgggbbb...",
      ".bbnlnnbffb.....bhbbnlnb..",
      ".bbbbbbbbbb.....bbbbbbbb..",
      ".bbbbbbbbbb.....bbbbbbbb.."
    ]
  },
  piccolo: {
    palette: {"a": "010101", "b": "000002", "c": "010301", "d": "87dd1e", "e": "040003", "f": "000000", "g": "3b9122", "h": "388341", "i": "010002", "j": "3e504b", "k": "77d131", "l": "722e97", "m": "732e98", "n": "a0d347", "o": "a03273", "p": "391b5e", "q": "a1644c", "r": "892d84", "s": "291744", "t": "451f6a"},
    rows: [
      ".........abbbc...........",
      ".......ccdddddcc.........",
      "......edddddddddc........",
      ".....fdggdcadddddbffff...",
      ".....fgggcddcddddcddddf..",
      "ef.bbggggghfdfddgdfbbbdff",
      "idciiggggghcdcdddjc.aadff",
      ".edccgggjdddccddddf...aff",
      ".bgddcggjdddddgggdde.....",
      "..bggdfghjjddddgdddc.....",
      "..egggdggg.jkddgdde......",
      "...aadgggg..jjgjji.......",
      ".....figgdd.j.gjb........",
      "......cjgdddddgga........",
      ".....ijgjddddddc.........",
      "..ieelggjhkddde..........",
      "eimmmmmhjghjccmii........",
      "cllllmlmghgghglmmee......",
      "cnooolllldddgddmmmlb.....",
      "fonnnofcccdddgdmmpna.....",
      "eoooonncddcedgfffpogcc...",
      ".fdddoonfeeaeedddbnoaa...",
      ".fgdddooennoooddeeeoaa...",
      "..bgggggqoodroacoonnooa..",
      "...eecgddddgcbggddqooof..",
      "......ifddoappbbcgddddc..",
      ".......fbefmjjjc.faiff...",
      ".......fjljlmmmc.........",
      ".......epmmmpslme........",
      "......blpmmmpslme........",
      "......blpmmmpslme........",
      "......flplmmpslme........",
      "......illmmmpslme........",
      "......illmmmpslme........",
      ".....fplmmmmpslmme.......",
      ".....iplmmmmsspmme.......",
      ".....iplmmmmsspmme.......",
      "...fflplmmlpbppmme.......",
      "...bblplmmpleplple.......",
      "..fpplpmmtmbmpmmlpf......",
      "..ipplpppmlblplllpc......",
      ".fmpplppllpepmpllpc......",
      ".fmpplmmmpbppplppla......",
      ".fmpppmmppbppppmmma......",
      ".bppppppplfpplpplpi......",
      ".bpppppple.fpplppf.......",
      "..bpppmli..apppppi.......",
      "..fssssi....fsssb........",
      ".iepppf......appi........",
      "bqqggrfb....firgbb.......",
      "eqqqqqqa....cqqqqa.......",
      ".fqqqqc......fqqa........",
      ".fqqqc.......fqqqaa......",
      ".fqqqc.......fqqqaa......",
      ".aqqqf.......fjqqqqb.....",
      "eqqqqf..................."
    ]
  },
  krillin: {
    palette: {"a": "000000", "b": "d28660", "c": "fadab4", "d": "f0f0f4", "e": "fa6e14", "f": "be2824", "g": "4854dc", "h": "9b483e", "i": "242878", "j": "96a0b4", "k": "242c3e", "l": "506070", "m": "e2be5a"},
    rows: [
      "..............aaaaa..............",
      "............aabccccaa............",
      "...........abcccccccca...........",
      "...........accccccbcbca..........",
      "..........abbbbccccccca..........",
      "..........abbbbccccbcba..........",
      "..........abbbbccccccca..........",
      "..........abbbbccccbcba..........",
      "..........acbbbaaccccca..........",
      "..........acabbccacccba....aaaaa.",
      "..........acbbcccaacaaba..accccca",
      "...........abbbccdacdaca..abbccca",
      "...........abbbccdacdaa...accbbba",
      "........aaefabbccccccaggaacaaccca",
      ".......aeeefbhhhhcaaeggeaaacccbba",
      ".......aiiefccccceeefaicccdaaggga",
      "..aaaaaiiifggggggeeffacccccaaggga",
      "..aaaaaiiifggggggeeffacccccaaggga",
      ".acccaaiiifiiiiiefffeaccbbbcccaa.",
      "accccaaaaaeeiigeeedjfaaaaabbba...",
      "accccaaaaaeeiigeeedjfaaaaabbba...",
      "acccbccabbbaeeeeejdffa..aaaaa....",
      ".cccbgggbbbafeeeefffa............",
      ".cccbgggbbbafeeeefffa............",
      "..aaaaaaaaaaiifeefaa.............",
      "...........aaiiggiga.............",
      "...........aaiiggiga.............",
      ".......aaaeeeegiieeeaa...........",
      ".....aaeeeeeggefggeeeaa..........",
      ".....aaeeeeeggefggeeeaa..........",
      "....aeeeeeffggffggfeeeefaa.......",
      "....feeeffffggffggaeeeefeea......",
      "....feeeffffggffggaeeeefeea......",
      "....effeffffaaaaaaafeeffeea......",
      "....eeeefffa......affffeeefaa....",
      ".....aaaaaaa.......affffeefaa....",
      ".....aaaaaaa.......affffeefaa....",
      ".....aakkka.........aaaa..lkka...",
      ".....aakkka............allllla...",
      ".....aammma.............aallla...",
      ".....aammma.............aallla...",
      "....kkkkkka.............aammma...",
      "..aaaaaaaa................alllaa.",
      "..........................aaaaaa.",
      "..........................aaaaaa."
    ]
  },
  beerus: {
    palette: {"a": "000000", "b": "0b0018", "c": "a687d7", "d": "af7afb", "e": "741ee7", "f": "7c19fc", "g": "f9ea51", "h": "df9212", "i": "ffe623", "j": "6d26c7", "k": "9b8cf1", "l": "831bcc", "m": "6329df", "n": "3b3d2c", "o": "e5912f", "p": "ee891c", "q": "efe8ee", "r": "3bafca", "s": "2f4745", "t": "f6fcfc", "u": "20b8d2", "v": "433c49", "w": "ad1411", "x": "ce231b", "y": "d5efe3", "z": "ecef2a", "A": "3ac4ec", "B": "1fcbf2", "C": "87837f", "D": "088fc6", "E": "0ed4fe", "F": "1687d8", "G": "216db7", "H": "0774be", "I": "24a0ca", "J": "0398db", "K": "ede3d1", "L": "11acdc", "M": "1e6d85", "N": "000e21", "O": "382016", "P": "4d1b00"},
    rows: [
      ".......aa.......................",
      ".......bcb......................",
      ".......addb.............aa......",
      ".......adddb...........ada......",
      ".......bdedda.........acda......",
      ".......bdfeda.........bdda......",
      "......aghefdca.......bceda......",
      "......ahigeeda......acbeda......",
      ".......bcjffedb.....adbeda......",
      ".......adefffdb....akaaeda......",
      ".......addfffbcb...bkbjdb.......",
      "........bdefebda..acbaeda.......",
      "........adbeebdbaaacbeedb.......",
      "........akbbaadjelbbbefdb.......",
      ".........bcbadddddddeedb........",
      "..........bkdeeeedddddea........",
      "...........aefffdddddddb........",
      "...........bffedddddeddmb.......",
      "..........aeffddddddeddda.......",
      "..........aeffddbbdddedda.......",
      "..........aeffddjgbbdeddb.......",
      "..........aefebddjgnbefb........",
      "..aa..aa...beeebmdjeeddba.......",
      "aaakaacb....aeebeedddddda.......",
      "akedbdb......abjffdddddja.......",
      "adedeeb........aaadddmbb........",
      "amdeddb........aopaeeb..........",
      ".bbdddaa..aaaaaqllebbbaa........",
      "...addga..aqqrrsqqqqqsra........",
      "....agia..acdtsnuvnvvrsqa.......",
      ".....ajgaagddatruvvwxvrya.......",
      ".....agzjjzhbbjqsvvxwnyooa......",
      "......acdeaabjddqvvnnqalja......",
      "......acdb...bddmqqqyabeb.......",
      ".......aa.....beededbppb........",
      "..............bjfefebppa........",
      "...........aaaAgvvvvgalaa.......",
      ".........aakkbBivqCnzaeeb.......",
      "........bcddbADinCqniaeb........",
      ".......bkdddbDBinvvviAb.........",
      "......addembBEEznCqnzBa.........",
      ".....acdeebFEEEznqCnzBDb........",
      ".....addebGHEEEzvvvvzBFHb.......",
      ".....bcdbIHJBEEznwKvzBJHIa......",
      "......bcbLHJJJDzvqwnzDFHLbaa....",
      ".......baLHDFHHznvngMHHHLbjdb...",
      "........aLHHHHHMgngMHHHINabjdb..",
      ".........aLHHLubagaILLLa...aaca.",
      ".........akIINa..aaaFIb......akb",
      ".........admb.......amb.......ba",
      ".........adb........aeaa......aa",
      "........awlba......aOPwa.......a",
      "........awOOa......aopa........a",
      "........agza........aOaa........",
      ".......awaa.........aOOwa.......",
      ".......aaaa.........aOOPwb......",
      "......aaaa......................"
    ]
  },
  whis: {
    palette: {"a": "000000", "b": "8c8c8c", "c": "ffffff", "d": "2196f5", "e": "dedede", "f": "616161", "g": "15bae8", "h": "80d8fe", "i": "651efe", "j": "fdc205", "k": "fdeb3d", "l": "029be5", "m": "b59dda", "n": "a30329", "o": "6a041c", "p": "1c2380", "q": "212121", "r": "fd5723", "s": "9e9e9e", "t": "424242"},
    rows: [
      "..............aaa.......................",
      "............a....aaa....................",
      "...........a...b..bca...................",
      "..........acbbbcb..bca..................",
      "..........acb..bcb..bca.................",
      "...........a...bcbb..ba.................",
      "............a..accb....a................",
      "...............accbb.b.a................",
      "...d...........accbb.b..a...............",
      "..ded..........accbb.bb.a...............",
      "..dfd..........accbb.bb.a...............",
      ".fdff.........abccbb.bb.a...............",
      ".fdff.........abccbb.bb.ba..............",
      "..dfd........acbbcbb.bb.ba..............",
      "..ded.......abcbbbgghbbbga..............",
      "..ede......abcbcccgghhhhha..............",
      "..eee......abbcbcgggiihhhha.............",
      "ajkkkja....abbbccggiggihhha.............",
      "akjjjka....abbbabggghhhghha.............",
      ".ajjja....hlabagiiggaaahhhah............",
      "..aja....hlccaagiiggcmahhaclh...........",
      "..aja....hlcccaggiggghhhhaclh...........",
      "..aka....hlccccaaiggghhhgaclh...........",
      "..aka.....hlccccagigghhhaclh............",
      "..aka..aaaahlcccaggighhaclhaaaa.........",
      "..aka.acccffhlaaannniiaalhffccca........",
      "..ada..affccfhfjkonnnkjfhfccffa....aa...",
      "..ada...afnncfhhfkkkkjhhfcnnfa....aha...",
      ".aapa....annncffhhhhhhffcnnna....ahgaaaa",
      ".ahgha...aoonncfkqqqqkfcnnooa...ahgghgha",
      ".agghaa..aoonncfkqqqqkfcnnooaaaaohhghaa.",
      "..ahggoaaoonaanckqrjqkcnaaanoonnoaaaaa..",
      "..ahhgonooaa.anckqrjqkcna..aooaaa.......",
      "..apaaaaooa...ankqrjqkna....aa..........",
      "..apa...aa.....akqrjqka.................",
      "..apa..........akqrjqka.................",
      "..ada..........akqrjqka.................",
      "..ada.........ankqqqqkna................",
      "..ada.........ankqqqqkna................",
      "..ada........anckqqqqkcna...............",
      "..ada........acfkqqqqkfca...............",
      "..aka.......acffkqscqkffca..............",
      "..aja.......afffkqcsqkfffa..............",
      "..aka......affffkqqqqkffffa.............",
      "..aka......afffckqcsqkcfffa.............",
      "..aka.....afffcokqscqkocfffa............",
      "..aka.....affcnokqqqqkoncffa............",
      "..aka....aafcnnokqjrqkonncfaa...........",
      "..aka....acconnokqrjqkonnocca...........",
      "..aka....anoonnookqqqkonnoona...........",
      "..aka...annoonnoookqkoonnoonoa..........",
      "..aka...annnonnooookooonnonnoa..........",
      "..aka..anonnnnnnoooooonnnnnnona.........",
      "..aja..anonnnnnnnnnnnnnnnnnnnna.........",
      "..aja..aannnnnnnnoononnnnnnnnaa.........",
      "..aja....annnnnnnoononnnnnnna...........",
      "..aja.....aaannnnonnonnnnaaa............",
      "..aja........aaanonnnaaaa...............",
      "..aja..........ascasa...................",
      "..aka..........accasa...................",
      "...a...........acsasa...................",
      "...a..........ascaasta..................",
      "..............acsaatta..................",
      "..............atca.atta.................",
      "..............ata..attta................",
      ".............atta......................."
    ]
  },
  trunks: {
    palette: {"a": "000000", "b": "9676ce", "c": "b39edc", "d": "6b1b9a", "e": "ffffff", "f": "986456", "g": "ffab92", "h": "9c9c9c", "i": "511a0f", "j": "02aaf7", "k": "0389d0", "l": "0c449d", "m": "767676", "n": "ffee3d", "o": "f54338"},
    rows: [
      "...........aabbbbbaaacca....",
      "..........abcbcccccddccca...",
      ".........accbccccbbbddccca..",
      "........accbccbcccccccdccca.",
      ".......abcbccbcccccccccdcca.",
      ".......abcbcbbccbccbbccddcca",
      ".......abbdcbbcbbcbddbcddcca",
      ".aa....abbdcbdcbbcbdddcddcca",
      "aeea...abbdcbdcbbcbfggfadcca",
      "aeha....abddcddcbcbfgggadca.",
      "aaaia...addaddfdddcbgggacca.",
      "...aia..adafaaffihddgggaca..",
      "....aia..aaffiffieeddga.a...",
      ".....aiaaeaffiffffejega.....",
      "......aeeaaaaiffffgggga.....",
      "......aehakkkaafffgggaaaa...",
      ".....aeehalkkkkafgggikkka...",
      ".....aeaaallllafiiiifjja....",
      "....aeaakkkjllkkffiffjjja...",
      "....aa.akkkljlkkmffifkjja...",
      ".......akkllljjkmmmmmkkaa...",
      "......akllllklkjjjeejkka....",
      "......akklaakkkmajhhjaka....",
      "......akkaeaaaamaaaaaajka...",
      ".....akkaeeeeeammaaaaakka...",
      ".....allaeeeeeannmmmfajjja..",
      ".....allaaeeeeanneoffakkka..",
      ".....akkkaaeeamaaeooaakggga.",
      ".....agggggaeamammamamagfga.",
      ".....aggiigaamammmamamaffga.",
      ".....afgifaeammmmmamammaga..",
      "......aggaeammmmmmamammaa...",
      ".......aaeaammmmaaaaammaa...",
      ".........aaammmamaaammmaa...",
      "........aaaammama.amamaaaa..",
      "........aaaaaaaa..aamaaaaa..",
      "........aaaaaaaa..aaaaaaaa..",
      "........aaaaaaaa..aaaaaaaa..",
      "........aaaaaaa....aaaaaa...",
      "........aaaaaa......affa....",
      "........annaa.......affa....",
      "........anna.........afa....",
      ".......afna..........afaa...",
      ".......affa..........affia..",
      "......aina...........affiia.",
      "......aiia.................."
    ]
  },
  jiren: {
    palette: {"a": "e64847", "b": "000000", "c": "9b9b9b", "d": "6b6b6b", "e": "4d4d4d", "f": "fff7f5", "g": "343434", "h": "fe0000", "i": "810505", "j": "b8b8b8"},
    rows: [
      "...................aaaaaaaa......a.........",
      "..................aaabbbbbaa.....a.........",
      ".................aabbcccccbaa...aa.........",
      "............a...aabdcddccccbaa.aaa.........",
      "............a...abdcddddccccba.aa..........",
      "............aa..abdddddddcccbaaa...........",
      "............aaa.abdddddddccccbaa...........",
      ".............aaaabdddddddccccba............",
      "..............aabdeddbbddccccba............",
      "...............abededbfbdcccdba............",
      "...............abededbbbbbccbaa............",
      "...............abddeddbbbcccba.............",
      "..............aaabeeddcccccdba.............",
      ".............aabbbddedccccdbaaaaaa.........",
      "........aaaaaabbbbdddecccdebaabbbaa.....a..",
      "...a...aabbbbbbbbbbbbbbeeebbbbgggbaa....a..",
      "...a..aabhibbbbbbbbbbbbbbbbbggggghbaa..aa..",
      "...aa.abhihhbbbbbbbbbbbbbbbbgggggihba.aaa..",
      "....a.abhihhhhibgggggggbbbbgggggihibaaaa...",
      "....aaabhihhhiihhhggggggbbbgggghihhhbaa....",
      ".....abihihhhiihhhhhgggggbgggghhihhhba.....",
      "....aabhiiiiiiihhhhhhgggggggghhhihhiba.....",
      "...aabiiihhhiiihhhhhhhgggggghhhhiiihba.....",
      "...abiiiihhhibihhhhhhhhbbbbhhhhhihihba.....",
      "a..abihhihhhbbiiiiiiiiiibbiiiiiihhihba.....",
      "aa.abhhhihbbaabiiiiiiihhhhhhhhihhhihbaa....",
      "aa.abhhhibaaaaabiiihiihhhhhhhhbbiiihbba....",
      ".aaabihhibafffaabbihiihhhhhhhbaabhhhfba....",
      ".aaaabiiibaafffaabihhihhhhhhbaaabffffba...a",
      "..aaabiiibbaffffaabhhhihhihhbafaabfffbaa..a",
      "....abffffbafffffabbhhhhhihhbaffabffffba.aa",
      "....abffffbafffffabbbbhhhihbbaffabjjjjbaaaa",
      "....abffffbaaafffabbbbbiiigbbaaaabfffjbaaa.",
      ".....abjjjjbbaafaabggbbgiggbgbaabfjffbaaa..",
      ".....aabfffffbafabggggbggggbgbaabfjffba....",
      "......abffjjfbaaabgggggggggbggbaabffbaa....",
      "......aabfjfjbaabgggggggggbgggbaaabbaa.....",
      ".......abffbbaabgggggbgggbgggbgbaaaaa......",
      ".......aabbaaaabggggbggbbbggbggba..........",
      "........aaaa..abgggbgggbbbggbggba..........",
      "..............abbbbbgggbbbggbggba..........",
      ".............aabgggbggbabbbbbgbaa..........",
      "............aabbgggbggbabbbbbbba...........",
      "............abbbgggbgbaaabbbbbbaa..........",
      "...........aabbbbbbbbaa.aabbbbbba..........",
      "...........abbbbbbbbaa...abbbbfba..........",
      "...........abbbbbbbba....abffffba..........",
      "...........abfbbbbbaa....abffffba..........",
      "...........abffffbaa.....aabfffba..........",
      "...........abjjjjba.......aabjjba..........",
      "..........aabjjjjba........abjjba..........",
      "..........ab..jjbaa........aabjbaa.........",
      "..........ab..jbaa..........ab..baaa.......",
      "..........ab..baa...........ab...bbaa......",
      ".........aab..ba............ab.....ba......",
      ".........ab...ba..........................."
    ]
  }
};

function crc32(buf) {
  let c, crc = 0xffffffff;
  for (let n = 0; n < buf.length; n++) {
    c = (crc ^ buf[n]) & 0xff;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    crc = (crc >>> 8) ^ c;
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
  const td = Buffer.concat([Buffer.from(type), data]);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(td));
  return Buffer.concat([len, td, crc]);
}
function encodePNG(w, h, rgba) {
  const raw = Buffer.alloc((w * 4 + 1) * h);
  for (let y = 0; y < h; y++) { raw[y * (w * 4 + 1)] = 0; rgba.copy(raw, y * (w * 4 + 1) + 1, y * w * 4, (y + 1) * w * 4); }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(h, 4); ihdr[8] = 8; ihdr[9] = 6; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0;
  return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]), chunk('IHDR', ihdr), chunk('IDAT', zlib.deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}
function toRGBA(sprite, scale = 1) {
  const h = sprite.rows.length, w = sprite.rows[0].length, W = w * scale, H = h * scale;
  const buf = Buffer.alloc(W * H * 4);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const k = sprite.rows[y][x]; if (k === '.') continue;
    const hex = sprite.palette[k], r = parseInt(hex.slice(0,2),16), g = parseInt(hex.slice(2,4),16), b = parseInt(hex.slice(4,6),16);
    for (let dy = 0; dy < scale; dy++) for (let dx = 0; dx < scale; dx++) {
      const i = ((y * scale + dy) * W + (x * scale + dx)) * 4; buf[i] = r; buf[i+1] = g; buf[i+2] = b; buf[i+3] = 255;
    }
  }
  return { W, H, buf };
}

if (require.main === module) {
  const args = process.argv.slice(2);
  const si = args.indexOf('--scale'); const scale = si >= 0 ? parseInt(args[si + 1], 10) : 0;
  const outDir = args.find((a, i) => !a.startsWith('--') && args[i - 1] !== '--scale') || '.';
  fs.mkdirSync(outDir, { recursive: true });
  for (const [name, s] of Object.entries(SPRITES)) {
    const a = toRGBA(s, 1); fs.writeFileSync(path.join(outDir, name + '.png'), encodePNG(a.W, a.H, a.buf));
    if (scale > 1) { const b = toRGBA(s, scale); fs.writeFileSync(path.join(outDir, `${name}_${scale}x.png`), encodePNG(b.W, b.H, b.buf)); }
    console.log(`${name}: ${s.rows[0].length}x${s.rows.length} -> ${path.join(outDir, name + '.png')}`);
  }
}
module.exports = { SPRITES, encodePNG, toRGBA };
