"""Vegeta head v10: authored as a fill-only grid (no outlines) following the official profile silhouette
(refs/vegeta/profile_head_ref.png), spikes exaggerated for chibi; outline added automatically.
h hair  H hair light  s skin  S skin shade  t deep shade  w eye white  k line/pupil   . empty"""
import os
from PIL import Image
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
#      0         1         2
#      012345678901234567890123456789
G = """\
...h..........................
...hh.........................
...hhh.....h..................
...hhhh...hh.....h............
...hhhhh.hhh....hh............
...hHhhhhhhhh..hhh.....h......
...hhHhhhhhHhhhhhh....hh......
...hhhHhhhhhHhhhhhh..hhh......
...hhhhHhhhhhHhhhhhhhhhh......
...hhhhhHhhhhhHhhhhhhhhhh.....
hh.hhhhhhhhhhhhhhhhhhhhhh.....
.hhhhHhhhhhhhhhhhhhhhhhhhh....
..hhhhHHhhhhhhhhhhhhhhhhhh....
...hhhhhhhhhhhhhhhhhhhhhhhh...
...hhhhhhhhhhhhhhhhhhsshhhh...
....hhhhhhhhhhhhhhhhssssshh...
hh...hhhhhhhhhhhhhhssssssss...
.hhhhHhhhhhhhhhhhhkksssssss...
..hhhhHHhhhhhhhhsssskkksssss..
...hhhhhhhhhhhsSsssssskkkss...
.....hhhhhhhhsStSssssswwkks...
......hhhhhhhsStSsssssSSssss..
....hhhhhhhhhsStSsSsssssssss..
.....hhhhhhhhsSSSssSSssssss...
......hhhhhhhhssssssssssksss..
........hhhhhhhsssssssskkss...
.........hhhhhhhSsssssssss....
...............SSssssssss.....
...............tSSSSSSSs......
................SSSSS.........
................SSSSS.........
"""
P = {'h': (44,42,54), 'H': (74,72,96), 's': (242,198,165), 'S': (215,159,123), 't': (174,120,98),
     'w': (249,245,236), 'k': (29,28,33)}
O = (29,28,33)
rows = G.splitlines(); W = max(len(r) for r in rows); H = len(rows)
im = Image.new('RGBA', (W + 2, H + 1), (0,0,0,0)); p = im.load()
for y, r in enumerate(rows):
    for x, c in enumerate(r):
        if c != '.': p[x + 1, y] = P[c] + (255,)
src = im.copy(); s = src.load()
for y in range(im.height):
    for x in range(im.width):
        nb = [(x+dx, y+dy) for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)) if 0 <= x+dx < im.width and 0 <= y+dy < im.height]
        if s[x, y][3] == 0:
            if any(s[n][3] for n in nb): p[x, y] = O + (255,)
        elif s[x, y][:3] in (P['h'], P['H']) and any(s[n][3] and s[n][:3] in (P['s'], P['S'], P['t']) for n in nb):
            p[x, y] = O + (255,)                          # hairline / ear edge
# neck stays open at the bottom (the body draws over it)
im.save(f'{R}/chars/vegeta_head.png'); print(im.size)
