"""Vegeta head v7: hair silhouette traced from the official profile art (refs/vegeta/profile_head_ref.png,
pixelized at 26 px), face hand-drawn on top: angry brow, narrow eye, pointed nose, frown, square jaw."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from PIL import Image
from pixelize import cutout, pixelize
from palette_map import snap
from pix import hx
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
ref = Image.open(f'{R}/refs/vegeta/profile_head_ref.png').convert('RGB')
p = snap(pixelize(cutout(ref, 30), width=26, colors=8, outline=True),
         [hx(x) for x in ('1d1c21', '2c2a36', 'f2c6a5', 'd79f7b', 'ae7862')])
W, H = p.size
# hair mask = every opaque pixel; we repaint the interior as hair and keep a clean 1px outline
g = [['.' if p.getpixel((x, y))[3] == 0 else 'h' for x in range(W)] for y in range(H)]
def put(x, y, c):
    if 0 <= x < W and 0 <= y < H: g[y][x] = c
def rect(x0, y0, x1, y1, c):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1): put(x, y, c)
def row(y, x0, s):
    for i, c in enumerate(s):
        if c != ' ': put(x0 + i, y, c)

# ---- face (front = right). ruler for x: 11..27
#            1111111111222222222
#            1234567890123456789
row(12, 11, "         sss      ")
row(13, 11, "        sssss     ")
row(14, 11, "       ssssssh    ")    # front lock of hair stays over the top of the forehead
row(15, 11, "      sssssssh    ")
row(16, 11, "   oooSsssssssh   ")    # ear top
row(17, 11, "  oSssoSsooossss  ")    # brow starts (far end high)
row(18, 11, "  osStsSssSooooss ")    # brow pushes down toward the nose
row(19, 11, "  osSts SswwooosSs")    # narrow eye: white then pupil at the front, nose bridge
row(20, 11, "  oSStsSsSSsssssso")    # cheekbone line, nose tip
row(21, 11, "   oSSssssSsssssso")
row(22, 11, "    ooSsssSsssssso")
row(23, 11, "      oSssSssoooso")    # frown: mouth line dips down at the front
row(24, 11, "      oSsssssSsso ")
row(25, 11, "       oSSssssssSo")    # square chin
row(26, 11, "        oSSSSSSSo ")
row(27, 11, "         ooooooo  ")
# clear stray hair pixels around the jaw / under the chin from the trace
for y in range(23, H):
    for x in range(0, 17):
        if g[y][x] == 'h': g[y][x] = '.'
for x in range(11, 28):
    if H > 28 and g[28][x] == 'h': g[28][x] = '.'
# neck
row(27, 13, "oSSo")
row(28, 13, "oSSo")
# hair highlight strands following the swept-back spikes
for (x, y) in ((6,3),(7,4),(8,5),(9,6),(10,7),(12,4),(13,5),(14,6),(15,7),(16,8),(5,8),(6,9),(7,10),(17,4),(18,5)):
    if g[y][x] == 'h': put(x, y, 'H')
# rebuild the outline: any hair/skin pixel touching transparency becomes outline
solid = {(x, y) for y in range(H) for x in range(W) if g[y][x] != '.'}
for (x, y) in list(solid):
    if g[y][x] in 'hH' and any((x+dx, y+dy) not in solid for dx, dy in ((1,0),(-1,0),(0,1),(0,-1))):
        g[y][x] = 'o'
PAL = """o 1d1c21
h 2c2a36
H 4a4860
s f2c6a5
S d79f7b
t ae7862
w f9f5ec"""
open(f'{R}/chars/vegeta_head.txt', 'w').write("# Vegeta head v7 (generated by tools/build_vegeta_head2.py)\n# palette\n" + PAL + "\n# grid\n" + '\n'.join(''.join(r) for r in g) + '\n')
print(W, H)
