"""Final package: every finished sprite (DBZ 9 + batch 2 (31) + batch 3) -> brightened -> final/native/,
8x previews, lineup, export/stickfight_sprites.js, zip."""
import os, sys, json, shutil
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from PIL import Image, ImageDraw
from brighten import brighten
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
DBZ = ['vegeta', 'piccolo', 'krillin', 'beerus', 'whis', 'trunks', 'jiren', 'android17', 'hit']
items = [(n, f'{R}/out/{n}.png') for n in DBZ]
for d in ('fit', 'b3'):
    items += [(f[:-4], f'{R}/out/{d}/{f}') for f in sorted(os.listdir(f'{R}/out/{d}')) if f.endswith('.png')]
shutil.rmtree(f'{R}/final', ignore_errors=True); os.makedirs(f'{R}/final/native'); os.makedirs(f'{R}/final/preview_8x')
for n, p in items:
    im = brighten(Image.open(p)); im.save(f'{R}/final/native/{n}.png')
    im.resize((im.width * 8, im.height * 8), Image.NEAREST).save(f'{R}/final/preview_8x/{n}_8x.png')
# lineup
names = sorted(n for n, _ in items); tiles = [(n, Image.open(f'{R}/final/native/{n}.png')) for n in names]
per = 12; rows = [tiles[i:i + per] for i in range(0, len(tiles), per)]
RH = max(t.height for _, t in tiles) + 12; W = max(sum(t.width + 8 for _, t in r) for r in rows) + 8
sh = Image.new('RGBA', (W, RH * len(rows)), (213, 225, 237, 255))
for r, row in enumerate(rows):
    x = 4
    for _, t in row: sh.alpha_composite(t, (x, (r + 1) * RH - t.height - 2)); x += t.width + 8
sh = sh.resize((sh.width * 4, sh.height * 4), Image.NEAREST); d = ImageDraw.Draw(sh)
for r, row in enumerate(rows):
    x = 4
    for n, t in row: d.text((x * 4, r * RH * 4 + 2), n, fill=(0, 0, 0)); x += t.width + 8
sh.save(f'{R}/final/all_lineup.png')
# export js (reuse the runtime from export/dbz_sprites.js)
src = open(f'{R}/export/dbz_sprites.js').read(); head_end, tail_start = src.index('const SPRITES = {'), src.index('function crc32')
KEYS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789#$%&*+-=?@!^~<>:;_|/[](){}'
parts = []
for n in names:
    im = Image.open(f'{R}/final/native/{n}.png').convert('RGBA'); px = im.load(); pal = {}; rows_ = []
    if len(im.getcolors(1 << 20)) > len(KEYS):
        im = im.convert('RGB').quantize(colors=len(KEYS) - 1, dither=Image.NONE).convert('RGBA'); a = Image.open(f'{R}/final/native/{n}.png').getchannel('A'); im.putalpha(a); px = im.load()
    for y in range(im.height):
        r_ = ''
        for x in range(im.width):
            c = px[x, y]
            if c[3] == 0: r_ += '.'; continue
            k = '%02x%02x%02x' % c[:3]
            if k not in pal: pal[k] = KEYS[len(pal)]
            r_ += pal[k]
        rows_.append(r_)
    parts.append(f"  {n}: {{\n    palette: {json.dumps({v: k for k, v in pal.items()})},\n    rows: [\n" + ',\n'.join('      ' + json.dumps(r) for r in rows_) + "\n    ]\n  }")
head = src[:head_end].split('\n'); head[1] = f'// StickFight sprites ({len(names)}), brightened, all face right. Generated by sprites/tools/build_final.py'
js = '\n'.join(head) + 'const SPRITES = {\n' + ',\n'.join(parts) + '\n};\n\n' + src[tail_start:]
open(f'{R}/export/stickfight_sprites.js', 'w').write(js); shutil.copy(f'{R}/export/stickfight_sprites.js', f'{R}/final/stickfight_sprites.js')
shutil.make_archive(f'{R}/stickfight_sprites_all', 'zip', f'{R}/final')
print(len(names), 'sprites')
