"""Vegeta native sprite (28x56), built on the proportions of the game's Luffy sprite. Writes chars/vegeta.txt."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
PAL = """o 1d1c21
h 2c2a36
H 4a4860
s f2c6a5
S d79f7b
t ae7862
w f9f5ec
m 7a3a3a
b 3c58c0
B 263c8c
a f2f2f6
A bcc2d4
g e8bc48
G a8822c"""
W, H = 28, 56
HAIR = """\
...........o................
..........oho.......o.......
.........ohho......oho......
...o.....ohhho....ohho......
...oo...ohhhho...ohhho...o..
...oho..ohhHho..ohhhho..oo..
....oho.ohhHhho.ohhhhoo.oho.
.o..ohhoohhHhhhoohhhhhoohho.
.oo.ohhhhhhHhhhhhhhHhhhhho..
..oohhhhhhhhhhhhhhhHhhhhho..
..ohhhhhhhhhhhhhhhhhhhhhho..
.oohhhhhHhhhhhhhhhhhhhhhhoo.
oohhhhhhHhhhhhhhhhhhhhhhhhho
.ohhhhhhhhhhhhhhhhhhhhhhhho.
..ohhhhhhhhhhhhhhhhhhhhhhho.
.oohhhhhhhhhhhhhhhhhhhhhhho.
..ohhhhhhhhhhhhhhhhhhhhhhho.
""".splitlines()
g = [list(r.ljust(W, '.')) for r in HAIR] + [['.'] * W for _ in range(H - len(HAIR))]
def put(x, y, c):
    if 0 <= x < W and 0 <= y < H: g[y][x] = c
def rect(x0, y0, x1, y1, c):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1): put(x, y, c)
def row(y, x0, s):
    for i, c in enumerate(s):
        if c != ' ': put(x0 + i, y, c)

# ---- face + body as full 28-px rows (x index ruler: 0123456789012345678901234567)
ROWS = {
17: "..ohhhhhhhhhhhhhhhhhhhhhhho.",
18: ".oohhhhhhhhhhhhhhhhhhhhhhho.",
19: "..ohhhhhhhshhhhhhhssshhhhho.",
20: "..ohhhhhhssssshhhhsssssshho.",   # V widow's peak, skin either side
21: "..ohhhhhSsssssshhssssssssso.",
22: ".oohhhhSsoooossshsooooossso.",   # far brow / peak tip / near brow (angry slope)
23: "..ohhhSSsssoossssssswwoooso.",   # eyes: far eye small, near eye white + pupil
24: "..ohhhStSsssssssssswwwoosso.",
25: "..ohhhSttSssssssssssssssso..",   # ear
26: "...ohhSSsssssssssSssssssoo..",
27: "...ohhoSssssssssssssmmmso...",   # scowl
28: "....oooSSssssssssssssoo.....",
29: ".......ooSSsssssssoo........",
30: "...ooooooooSSSSSSoooooooo...",
31: "..oggggGoaaaaaaaaaaaoggggGo.",
32: "..oggggggoaaaaaAaaaaogggggo.",
33: "..oGgggGobaaaaaAaaaabGgggGo.",
34: "...oGGGobbaaaaaAaaaabbGGGo..",
35: "...obbbooooooooooooooooobo..",
36: "...obbbobbbbbbbbbbbbbaaaoo..",
37: "..oaaaobbBBBBBBBBBBBBaaAAo..",
38: "..oaaAAoooooooooooooooaAo...",
39: "...oAAoaaaaaaaaAaaaaaaoo....",
40: "....ooaaaaaaaaaAaaaaaaAo....",
41: ".....oAAAAAAAAAAAAAAAAAo....",
42: ".....oggGbbbbbbbbbbbGggo....",
43: ".....oGGobbbbbbbbbbbbGGo....",
44: "......oobbbbbbboobbbbbo.....",
45: "......obbbbBo..obbbbbBo.....",
46: "......obbbbBo..obbbbbBo.....",
47: "......obbbbBo..obbbbbBo.....",
48: ".....oaaaaAo...oaaaaaAo.....",   # tall white boots
49: ".....oaaaaAo...oaaaaaAo.....",
50: "....oaaaaaAo...oaaaaaaAo....",
51: "....oaaaaaAo...oaaaaaaAo....",
52: "...oaaaaaaAo...oaaaaaaaAo...",
53: "..oggaaaaaAo...oaaaaaaagggo.",   # gold toe caps
54: ".oggggAAAAAo...oAAAAAAAggggo",
55: ".oooooooooo.....ooooooooooo.",
}
for y, r in ROWS.items():
    assert len(r) == W, (y, len(r))
    g[y] = list(r)
with open(os.path.join(HERE, '..', 'chars', 'vegeta.txt'), 'w') as f:
    f.write("# Vegeta (classic Saiyan armour) - native sprite, faces right. Generated by tools/build_vegeta.py\n# palette\n" + PAL + "\n# grid\n")
    f.write('\n'.join(''.join(r) for r in g) + '\n')
